# Generated by Django 5.2 on 2025-04-30 16:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_file', models.FileField(upload_to='certificate_templates/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificate_backgrounds/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificate_signatures/')),
                ('title_text', models.CharField(default="Certificat d'Accomplissement", max_length=200)),
                ('body_text', models.TextField(default='Ce certificat est décerné à {student_name} pour avoir complété avec succès le cours {course_title}.')),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_valid', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
