# Generated by Django 5.2 on 2025-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.PositiveIntegerField(
                default=0, help_text="Durée estimée du cours en heures"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="objectives",
            field=models.TextField(
                blank=True, help_text="Objectifs d'apprentissage pour ce cours"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.TextField(
                blank=True,
                help_text="Connaissances préalables nécessaires pour ce cours",
            ),
        ),
    ]
