# Generated by Django 5.2 on 2025-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_duration_course_objectives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("published", "Publié"),
                    ("archived", "Archivé"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
